replicas:
  min: 1
  max: 16
  resource:
    cpu:
      utilization: 50

image:
  repository: aicacia/api-p2p
  tag: latest
  pullPolicy: Always
  hash: sha256:13ba025b6c186da3fdce3db68f192721fef8300ae02f2ae76c953d771b7180e4

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: p2p.aicacia.com
      paths:
        - /
  tls:
    - secretName: p2p-aicacia-com-tls
      hosts:
        - p2p.aicacia.com

resources:
  requests:
    cpu: 15m
    memory: 184M
  limits:
    cpu: 250m
    memory: 512M
